package com.stagepfa.demo.domain.enums;

public enum LedgerMovementType {
    MONTHLY_ACCRUAL, CARRY_OVER, APPROVED_LEAVE_DEBIT, CANCELLED_LEAVE_CREDIT,
    HR_ADJUSTMENT_CREDIT, HR_ADJUSTMENT_DEBIT, CORRECTION_CREDIT, CORRECTION_DEBIT
}
